---

- name: install ovn_central
  hosts: ovn_central
  become: yes
  tasks:

    - name: update dnf
      dnf:
        name: "*"
        state: latest

    - name: install ovn_central
      import_role:
        name: ovn_central
      vars:
        ovn_central_action: install
      tags: install_ovn_central
