---

- name: start ovn_central
  hosts: ovn_central
  become: yes
  tasks:

    - name: start ovn_central
      import_role:
        name: ovn_central
      vars:
        ovn_central_action: start
      tags: install_ovn_central
