---

- name: make dir
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ovs_etc_dir }}"
    - "{{ ovs_log_dir }}"
    - "{{ ovs_run_dir }}"
    - "{{ ovn_etc_dir }}"
    - "{{ ovn_log_dir }}"
    - "{{ ovn_run_dir }}"

- name: check nb db
  stat:
    path: "{{ ovn_etc_dir }}/{{ ovn_nb_db_name }}.db"
  register: nb_db

- name: create nb db schema
  command: >-
    ovsdb-tool create 
      {{ ovn_etc_dir }}/{{ ovn_nb_db_name }}.db
      {{ ovn_nb_db_schema_file_path }}
  changed_when: true
  when: not (nb_db.stat.exists | bool)

- name: check sb db
  stat:
    path: "{{ ovn_etc_dir }}/{{ ovn_sb_db_name }}.db"
  register: sb_db

- name: create sb db schema
  command: >-
    ovsdb-tool create
      {{ ovn_etc_dir }}/{{ ovn_sb_db_name }}.db
      {{ ovn_sb_db_schema_file_path }}
  changed_when: true
  when: not (sb_db.stat.exists | bool)

- name: check nb server
  stat:
    path: "{{ ovn_run_dir }}/{{ ovn_nb_db_name }}.pid"
  register: nb_server

- name: run nb db
  command: >-
    ovsdb-server {{ ovn_etc_dir }}/{{ ovn_nb_db_name }}.db
      --remote=punix:{{ ovn_run_dir }}/{{ ovn_nb_db_name }}.sock
      --remote=ptcp:{{ ovn_nb_port }}
      --pidfile={{ ovn_run_dir }}/{{ ovn_nb_db_name }}.pid
      --detach
      --log-file={{ ovn_log_dir }}/{{ ovn_nb_db_name }}.log
  changed_when: true
  when: not (nb_server.stat.exists | bool)

- name: check sb server
  stat:
    path: "{{ ovn_run_dir }}/{{ ovn_sb_db_name }}.pid"
  register: sb_server

- name: run sb db
  command: >-
    ovsdb-server {{ ovn_etc_dir }}/{{ ovn_sb_db_name }}.db
      --remote=punix:{{ ovn_run_dir }}/{{ ovn_sb_db_name }}.sock
      --remote=ptcp:{{ ovn_sb_port }}
      --pidfile={{ ovn_run_dir }}/{{ ovn_sb_db_name }}.pid
      --detach
      --log-file={{ ovn_log_dir }}/{{ ovn_sb_db_name }}.log
  changed_when: true
  when: not (sb_server.stat.exists | bool)

- name: init nb db
  command: >-
    ovn-nbctl
      --db unix:{{ ovn_run_dir }}/{{ ovn_nb_db_name }}.sock
      --no-wait
      init
  changed_when: true
  when: not (nb_server.stat.exists | bool)

- name: init sb db
  command: >-
    ovn-sbctl
      --db unix:{{ ovn_run_dir }}/{{ ovn_sb_db_name }}.sock
      init
  changed_when: true
  when: not (sb_server.stat.exists | bool)

- name: check northd
  stat:
    path: "{{ ovn_run_dir }}/northd.pid"
  register: northd

- name: run northd
  command: >-
    ovn-northd
      --pidfile={{ ovn_run_dir }}/northd.pid
      --detach
      --log-file={{ ovn_log_dir }}/northd.log
      --ovnnb-db=unix:{{ ovn_run_dir }}/{{ ovn_nb_db_name }}.sock
      --ovnsb-db=unix:{{ ovn_run_dir }}/{{ ovn_sb_db_name }}.sock
  changed_when: true
  when: not (northd.stat.exists | bool)

- name: port open
  firewalld:
    zone: public
    port: "{{ item }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - "{{ ovn_nb_port }}"
    - "{{ ovn_sb_port }}"
